spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ashreddy@1020
    url: jdbc:mysql://localhost:3306/Feign
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
springdoc:
  swagger-ui:
     path: swagger-ui.html
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
